# https://cert-manager.io/docs/configuration/acme/dns01/cloudflare/
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-dns01
spec:
  acme:
    email: a.r.kakde@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-dns01-private-key
    solvers:
      - dns01:
          cloudflare:
            email: a.r.kakde@gmail.com
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token