# First
apiVersion: v1
kind: Service
metadata:
  name: notebook-app-first
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: notebook-app-first
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notebook-app-first
spec:
  selector:
    matchLabels:
      app: notebook-app-first
  replicas: 1
  template:
    metadata:
      labels:
        app: notebook-app-first
    spec:
      containers:
        - name: notebook-app-container
          image: ani2fun/note-book:83af8c55ac06e279b054652d1f291ba3214428a2
          imagePullPolicy: Always
          ports:
            - containerPort: 3000