# First
apiVersion: v1
kind: Service
metadata:
  name: portfolio-app-first
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: portfolio-app-first
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-app-first
spec:
  selector:
    matchLabels:
      app: portfolio-app-first
  replicas: 1
  template:
    metadata:
      labels:
        app: portfolio-app-first
    spec:
      containers:
        - name: portfolio-app-container
          image: ani2fun/portfolio-app:fec370afb45c92196d307d624df718b99aaf8cb3
          ports:
            - containerPort: 3000